### ISSUE TITLE
FMI & IPP broken at 12.02.2018

### ISSUE THREAD

**Issue by mammuth** [jpbernius/FMeat.php#1]
hunger.tum.sexy shows _An error occured while fetching the FMI Bistro menu._ I guess that's an issue within this lib then?

**Comment by jpbernius** [comment]
Apparently, there was some problem parsing the menus for both locations in [srehwald/eat-api](https://github.com/srehwald/eat-api).

**Comment by mammuth** [comment]
👍 
For the reference: https://github.com/srehwald/eat-api/issues/19
