### ISSUE TITLE
Mediziner Mensa

### ISSUE THREAD

**Issue by kordianbruck** [jpbernius/FMeat.php#2]
> könnt ihr auch die MedizinerMensa im rechts der Isar dazunehmen?

https://www.med.fs.tum.de/index.php?id=5
bottom right. 

https://www.med.fs.tum.de/fileadmin/w00bps/www/Daten/Mensaplan/KW_08_Winter_3_Mensa_Aktion_Huettenschmankerl.pdf

**Comment by kordianbruck** [comment]
We would love to setup the TUM Campus App with fmeat, so we can provide _ALL OF THE MENSAS_ :tada:

**Comment by jpbernius** [comment]
Closing this, as there is no necessary change to this library at the moment.
